### ISSUE TITLE
API connect dev toolkit fails to start DataPower gateway

### ISSUE THREAD

**Issue by bmccann36** [ibm-datapower/datapower-tutorials#13]
OS: Mac Catalina 10.15.7   
Node version: 10.23.0 (using nvm)   
IBM API-connect version: API Connect: v5.0.8.6-iFix (npm package verion: apiconnect v4.0.29)

I am trying to carry out the steps described in the api connect tutorial

I would like to use the API designer locally and test it using datapower gateway. I run into issues at the step where I hit the play button

[![play button][1]][1]

I always get this error

`      Service apiconnect started but did not initialize within the timeout period. Dumping log buffer.
Invalid app (app is not a file or a directory ), try sl-run --help.`

same thing happens when I run `apic start` to try to start the GW via the apic cli

## steps
- I run `apic edit`   
- API-C console comes up in browser   
- I hit the play button to start the gateway, If docker images don't exist locally it downloads the base images and builds the images successfully 

[![enter image description here][2]][2]

```
Building datapower-mgmt-server-lite
.....
Successfully built 1cfea0880318
Successfully tagged ibm-apiconnect-toolkit/datapower-mgmt-server-lite:1.1.10
....
Building datapower-api-gateway
....
Successfully built 73fa564f22e6
Successfully tagged ibm-apiconnect-toolkit/datapower-api-gateway:1.1.10
```

but this is as far as I ever get, the Docker containers never start and thus API gateway never configures itself with the DP gateway. I see this error after a few seconds

[![enter image description here][3]][3]

It seems that the issue has to do the the package strongloop witch does the process management and coordinates among the processes 

in `.apiconnect/strong-pm/start.log` I see:
```
Unexpected exit with 1 from Runner: commit apiconnect/local-directory
Start Runner: commit apiconnect/local-directory
Invalid app (app is not a file or a directory ), try `sl-run --help`.
```

the really odd thing is that I had it working a few days ago...
why it doesn't work now is my unsolved mystery 

  [1]: https://i.stack.imgur.com/BjyI7.png
  [2]: https://i.stack.imgur.com/PTjEH.png
  [3]: https://i.stack.imgur.com/7y4OS.png

**Comment by bmccann36** [comment]
@tonyffrench @ozairs  sorry to chase you all down for tech support,
Any idea what could be causing this? I've tried with a few of the other apiconnect npm package versions and can't get those to work either.

**Comment by ozairs** [comment]
I suggest posting here: https://community.ibm.com/community/user/middleware/communities/community-home?CommunityKey=2106cca0-a9f9-45c6-9b28-01a28f4ce947

**Comment by bmccann36** [comment]
@ozairs thanks!
